# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1


jobs:
  build_job:
    docker:
      - image: cimg/base:stable
    steps:     
      - run: exit 0
      - run: 
          command: echo "This is a error command"
          when: on_fail

workflows:
  validate_workflow:
    jobs:
      - build_job
