# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1


jobs:
  build:
    docker: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm_packages"
          paths:
            /src/node_module
      - run: npm run lint

  test:
    docker: circleci/node:13.8.0
    steps:
      - checkout      
      - restore_cache:
        keys: 
          - "npm_packages"
      - run: npm -i
      - run: npm run test


  analyze:
    docker: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
        keys: 
          - "npm_packages"
      - run: npm audit


workflows:
  validate_workflow:
    jobs:
      - build
      - test:
        requires:
          - build
      - analyze:
        requires:
          - test
